### ISSUE TITLE
Accept a more generic Accumulate

### ISSUE THREAD

**Issue by ktosiek** [exercism/idris#45]
I think this solution should be accepted by the tests: http://exercism.io/submissions/bec1bec2b70847588ca3dad4b52cc3b6

This could be accomplished by changing the type of `assertEq` to be more specific. Do you think it's a good idea?

**Comment by yurrriq** [comment]
We should use [idris-testing](https://github.com/yurrriq/idris-testing) or, better yet, Specdris (#43).

**Comment by yurrriq** [comment]
That's not the real issue here though. Let me try to elaborate.


Altering the bespoke `assertEq` to be more specific is not the correct approach here.

```idris
assertEq : Eq a => String -> (given : a) -> (expected : a) -> IO ()
```

It specifies that `assertEq` means to compare two values of type `a`, under the constraint that `a` has an implementation of `Eq`. [The implementation you linked](http://exercism.io/submissions/bec1bec2b70847588ca3dad4b52cc3b6) does not satisfy that invariant, because the type checker cannot be sure that `b` has an implementation of `Eq`. The solution to your generic implementation then is to add the constraint:

```idris
accumulate : Eq b => (a -> b) -> List a -> List b
```


What all that said, the tests expect the solution to have the following signature, as per [the stub](https://github.com/exercism/idris/blob/master/exercises/accumulate/src/Accumulate.idr).

```idris
accumulate : (Int -> Int) -> List Int -> List Int
```

Notably, the following test fails to type check when you alter the signature of `accumulate`, as in the [linked solution](http://exercism.io/submissions/bec1bec2b70847588ca3dad4b52cc3b6).

```idris
testDecrementFunctionAddsOneToAllInput : IO ()
testDecrementFunctionAddsOneToAllInput = assertEq "decrement function subtracts 1 from input" (accumulate (\x => x - 1) [1,2,3]) [0,1,2]
```

```
When checking right hand side of testDecrementFunctionAddsOneToAllInput with expected type
        IO ()

When checking argument smaller to function Prelude.Nat.-:
        Can't find a value of type
                LTE 1 x
```


So if we want to support a more generic `accumulate` (I can see arguments both ways), the necessary changes are more broad in scope than just `assertEq`.

#### Hot take re: making `accumulate` generic
- *Pros*: more traditional FP, good learning exercise, intro to type constraints
- *Cons*: could be too much too soon (intro to type constraints), need to change most/all of test (not a big deal, obviously)


I've had a long day/week. Does this blathering make any sense?

**Comment by ktosiek** [comment]
It does make sense.

I still believe generalising the signature should be accepted by tests, even if the stub stays the same.

The type errors you've cited stem from the compiler either not specialising `b` (the empty list case), or selecting a wrong type for numbers (the `LTE 1 x` case). Both cases could be solved by specifying the type of lists used in tests. That's what my proposition really does, by specialising the `assertEq` helper.
