### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by thosgood** [exercism/idris#60]
I'm interested in helping to launch the Idris track, but it doesn't seem like there's been any activity here for quite a while. What things need to be done still?

**Comment by yurrriq** [comment]
My schedule these days is such that I don't have much free time at all for stuff like this. Maybe @kytrinyx and/or @NobbZ can advise on how you can help. Thanks for your interest!

**Comment by NobbZ** [comment]
Idris is a come and go for me. I'm personally interested in the field of dependant types, but I have noone at my side who helps me when I struggle, so I probably won't be able to take over this track soon ;)

I'd like to help where I can though to get this track up and running, but I need some advice, what to do next…

**Comment by yurrriq** [comment]
I can try my best to help out with reviewing and answering questions, but my time is limited and (travel) schedule is messy.

**Comment by guygastineau** [comment]
@NobbZ I am in a similar position as you.  You also are a Haskell enthusiast, right? (I remember you subtly pointed me toward it when I was still mistakenly fetishizing Golang ;) )

I am an idiot who manages all my Haskell tools through a user level global cabal installation that is not managed by pacman, so I need to recompile everything (xmonad + its tools, Idris, and some other stuff), because trying to upgrade Idris this morning put me in dependency hell ;)

Luckily I can still do the exercise here, but my Idris version is missing a couple features that `'idris-mode` is expecting in emacs.

Anyway, my suggestion is that (whether we end up helping maintain this project or not (I think we are both very involved in other tracks)) we might be good resources/sounding blocks for each other as co-learners/explorers of dependently typed programming!
